version: '3'

services:
  mongo-ui:
    container_name: mongo-ui
    image: mongo-express
    ports:
      - "8081:8081"
    environment:
      ME_CONFIG_BASICAUTH_USERNAME: thyagofr
      ME_CONFIG_BASICAUTH_PASSWORD: mongo-express
      ME_CONFIG_MONGODB_PORT: 27017
      ME_CONFIG_MONGODB_ADMINUSERNAME: thyagofr
      ME_CONFIG_MONGODB_ADMINPASSWORD: password
      ME_CONFIG_MONGODB_SERVER: articles-mongodb
    restart: unless-stopped
    links:
      - articles-mongodb
    depends_on:
      - articles-mongodb
    networks:
      - space-flight-api-network
  articles-mongodb:
    container_name: articles-mongodb
    image: mongo
    environment:
      MONGO_INITDB_ROOT_USERNAME: thyagofr
      MONGO_INITDB_ROOT_PASSWORD: password
    ports:
      - "27017:27017"
    networks:
      - space-flight-api-network
  zookeeper:
    container_name: zookeeper
    image: confluentinc/cp-zookeeper:latest
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    networks:
      - space-flight-api-network
  kafka-broker-1:
    container_name: kafka-broker-1
    image: confluentinc/cp-kafka:latest
    depends_on:
      - zookeeper
    ports:
      - "9092:9092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka-broker-1:29092,PLAINTEXT_HOST://localhost:9092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
    networks:
      - space-flight-api-network
  kafdrop:
    container_name: kafdrop
    image: obsidiandynamics/kafdrop:latest
    depends_on:
      - kafka-broker-1
    ports:
      - "19000:9000"
    environment:
      KAFKA_BROKERCONNECT: kafka-broker-1:29092
    networks:
      - space-flight-api-network

networks:
  space-flight-api-network:
    driver: bridge
