version: '3'

services:
  mongo-ui:
    container_name: mongo-ui
    image: mongo-express
    ports:
      - "8081:8081"
    environment:
      ME_CONFIG_BASICAUTH_USERNAME: thyagofr
      ME_CONFIG_BASICAUTH_PASSWORD: mongo-express
      ME_CONFIG_MONGODB_PORT: 27017
      ME_CONFIG_MONGODB_ADMINUSERNAME: thyagofr
      ME_CONFIG_MONGODB_ADMINPASSWORD: password
    links:
      - articles-mongodb
    depends_on:
      - articles-mongodb
  articles-mongodb:
    container_name: articles-mongodb
    image: mongo
    environment:
      MONGO_INITDB_ROOT_USERNAME: thyagofr
      MONGO_INITDB_ROOT_PASSWORD: password
    ports:
      - "27017:27017"